src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Form\Extension\Core\Type\DateType;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Nom ne peut pas être vide.')]
    #[Assert\Length(max: 8, maxMessage: 'Nom ne peut pas dépasser {{ limit }} caractères.')]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Description ne peut pas être vide.')]
    #[Assert\Length(max: 255, maxMessage: 'contient au moins {{ limit }} caractères.')]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Lieu ne peut pas être vide.')]
    #[Assert\Length(min: 8, maxMessage: 'Lieu contient au moins  {{ limit }} caractères.')]
    private ?string $lieu = null;
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\OneToMany(targetEntity: Participation::class, mappedBy: 'event')]
    private Collection $participations;

    #[ORM\Column]
    private ?int $nbvue = 0;

    public function getNbVue(): ?int
    {
        return $this->nbvue;
    }

    public function setNbVue(?int $nbvue): self
    {
        $this->nbvue = $nbvue;

        return $this;
    }
    public function __construct()
    {
        $this->participations = new ArrayCollection();
    }



    
    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): static
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setEvent($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): static
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getEvent() === $this) {
                $participation->setEvent(null);
            }
        }

        return $this;
    }
    public function __toString(): string
{
    return $this->nom ?? ''; 
}
    
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('image', FileType::class, [
                'label' => 'Votre Image (JPG, JPEG, PNG file)',
                'mapped' => false,
                'required' => false,
                'attr' => ['accept' => 'image/*'],
            ])
            ->add('lieu')
            ->add('date', DateType::class, [
                'widget' => 'single_text', // Utilise un élément input de type date, permettant aux navigateurs de fournir un sélecteur de date
                'attr' => ['class' => 'my-date-class'], // Classe CSS personnalisée si nécessaire
                'label' => 'Date de l\'événement',
                // autres options...
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Participation;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use UltraMsg\WhatsAppApi;
use Symfony\Component\Security\Core\Security;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }
    #[Route('/front', name: 'app_event_indexf', methods: ['GET'])]
    public function indexf(EventRepository $eventRepository): Response
    {
        return $this->render('event/indexf.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,SluggerInterface $slugger): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
              /** @var UploadedFile $imageFile */
              $imageFile = $form->get('image')->getData();

              if ($imageFile) {
                  $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                  $safeFilename = $slugger->slug($originalFilename);
                  $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
  
                  try {
                      $imageFile->move(
                          $this->getParameter('img_directory'),
                          $newFilename
                      );
                  } catch (FileException $e) {
                  }
  
                  $event->setImage($newFilename);
              }
            $entityManager->persist($event);
            $entityManager->flush();
            $nom = $event->getNom();
            $description = $event->getDescription(); 
            $date = $event->getDate()->format('Y-m-d'); 
        
            $this->envoyerMessageWhatsApp($nom, $description, $date);
                    $this->addFlash('success', 'Evenement est Ajouter.');

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

  

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);

    }
    #[Route('ffdf/{id}', name: 'app_event_showf', methods: ['GET'])]
    public function showd(Event $event,EntityManagerInterface $entityManager): Response
    {
        $currentViews = $event->getNbVue();



        $nb=$currentViews+1;
        $event->setNbVue($nb);


        $entityManager->persist($event);
        $entityManager->flush();
        return $this->render('event/showf.html.twig', [
            'event' => $event,
        ]);
      
    }

    #[Route('/what', name: 'whatsapp')]
    public function envoyerMessageWhatsApp($nom, $description, $date): Response
    {
        require_once __DIR__ . '/../../vendor/autoload.php'; 
        $ultramsg_token = "lz7xjqxr6f1yz3vh"; 
        $instance_id = "instance80575"; 
    
        $client = new WhatsAppApi($ultramsg_token, $instance_id);
    
        $to = "+21653256173"; 
        $body = "Bonjour Monsieur Idriss,\n\nNous vous informons qu'un nouveau Event a été Ajouter dans notre système. Voici les détails :\n\Nom : $nom\Description : $description\nDate d'ajouteé : $date\n\nVeuillez prendre les mesures nécessaires pour examen et suivi.\n\nCordialement.";
    
        $api = $client->sendChatMessage($to, $body);
    
        $image = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Info_Simple.svg/512px-Info_Simple.svg.png";
        $caption = "Image Caption";
        $priority = 10;
        $referenceId = "SDK";
        $nocache = false;
        $imageApi = $client->sendImageMessage($to, $image, $caption, $priority, $referenceId, $nocache);
    
        print_r($api); 
        print_r($imageApi); 
    
        return new Response('WhatsApp messages sent successfully!');
    }
    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();
    
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
    
                try {
                    $imageFile->move(
                        $this->getParameter('img_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
    
                $event->setImage($newFilename);
            }
    
            $entityManager->flush();
            $this->addFlash('success', 'Le Event a été modifié avec succès.');

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }
    

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }
        $this->addFlash('success', 'L\'Event a été supprimer avec succès.');

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('bcc/{id}', name: 'app_event_deletef', methods: ['POST'])]
    public function deleteb(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }
        $this->addFlash('success', 'L\'Event a été supprimer avec succès.');

        return $this->redirectToRoute('app_event_indexf', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_delete_formf.html.twig
<form method="post" action="{{ path('app_event_deletef', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}




{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <div class="card shadow mb-4">
        <div class="card-header py-3" style="display: flex; justify-content: space-between; align-items: center;">
            <h6 class="m-0 font-weight-bold text-primary">MANAGE EVENTS</h6>
            <a href="{{ path('app_event_new') }}" class="btn btn-success btn-icon-split">
                <span class="text">ADD EVENT</span>
            </a>
        </div>
  
        <div class="card-body">
       <div class="input-group no-border">
            <input type="text" value="" class="form-control" placeholder="Search..." id="myInput">
            <button type="submit" class="btn btn-default btn-round btn-just-icon"></button>
        </div>
            <div class="table-responsive">
                <table  id="anotherTable"    id="dataTable"class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th onclick="sortTable(0)">Name</th>
                            <th onclick="sortTable(1)">Description</th>
                            <th onclick="sortTable(2)">Lieu</th>
                            <th onclick="sortTable(3)">Date</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for event in events %}
                        <tr>
                            <td>{{ event.nom }}</td>
                            <td>{{ event.description }}</td>
                            <td>{{ event.lieu }}</td>
                            <td>{{ event.date ? event.date|date('Y-m-d ') : 'N/A' }}</td>
                            <td><img src="{{ asset('img/' ~ event.image) }}" alt="#" style="height: 50px; width: auto;"></td>
                            <td>
                                <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-primary btn-icon-split">
                                    <span class="text">Show</span>
                                </a>
                                <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning btn-icon-split">
                                    <span class="text">Edit</span>
                                </a>
                             
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="6">No records found</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    function sortTable(n) {
        var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("anotherTable");
        switching = true;
        dir = "asc";

        while (switching) {
            switching = false;
            rows = table.rows;

            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];

                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }

            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchcount++;
            } else {
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
</script>

{% endblock %}

templates/event/indexf.html.twig
{% extends 'client/index.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
<style>
    .event-card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease;
    }

    .event-card:hover {
        transform: translateY(-5px);
    }

    .event-image {
        height: 150px;
        object-fit: cover;
    }

    .event-title {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .event-details {
        font-size: 16px;
        color: #555;
        margin-bottom: 10px;
    }

    .event-icons a {
        margin-right: 5px;
        transition: all 0.3s ease;
    }

    .event-icons a:hover {
        transform: scale(1.1);
    }
</style>

<div class="container">
    <div class="row">
        {% for event in events %}
        <div class="col-md-4 mb-4">
            <div class="card event-card">
                <img src="{{ asset('img/' ~ event.image) }}" class="card-img-top event-image" alt="#" style="height: 150px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title event-title">{{ event.nom }}</h5>
                    <p class="card-text event-details">{{ event.description }}</p>
                    <p class="card-text event-details">
                        <strong>Lieu:</strong>
                        {{ event.lieu }}
                    </p>
                    <p class="card-text event-details">
                        <strong>Date:</strong>
                        {{ event.date ? event.date|date('Y-m-d ') : '' }}
                    </p>
                    <div class="btn-group event-icons" role="group">
                        <a href="{{ path('app_participation_newp', {'eventId': event.id}) }}" class="btn btn-primary">Participate</a>
                        <a href="{{ path('app_event_showf', {'id': event.id}) }}" class="btn btn-success rounded-pill py-2 px-4">
                            <i class="fa fa-eye ">{{ event.nbVue }}</i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-12">
            <p>No records found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/event/new.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('app_event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ event.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
				<td><img src="{{ asset('img/' ~ event.image) }}" class="card-img-top" alt="#"></td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ event.lieu }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ event.date ? event.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_event_index') }}">back to list</a>


{% endblock %}

templates/event/showf.html.twig
{% extends 'client/index.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ event.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
				<td><img src="{{ asset('img/' ~ event.image) }}" class="card-img-top" alt="#" style="width: 30%; height: auto;">
</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ event.lieu }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ event.date ? event.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_event_indexf') }}">back to list</a>

    
{% endblock %}